[2023-07-11T12:19:05.089+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.train_ordinal_impute manual__2023-07-11T12:17:54.699607+00:00 [queued]>
[2023-07-11T12:19:05.110+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.train_ordinal_impute manual__2023-07-11T12:17:54.699607+00:00 [queued]>
[2023-07-11T12:19:05.111+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-11T12:19:05.139+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): train_ordinal_impute> on 2023-07-11 12:17:54.699607+00:00
[2023-07-11T12:19:05.150+0000] {standard_task_runner.py:57} INFO - Started process 544 to run task
[2023-07-11T12:19:05.160+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'train_ordinal_impute', 'manual__2023-07-11T12:17:54.699607+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmpn_qnqctp']
[2023-07-11T12:19:05.161+0000] {standard_task_runner.py:85} INFO - Job 490: Subtask train_ordinal_impute
[2023-07-11T12:19:05.251+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.train_ordinal_impute manual__2023-07-11T12:17:54.699607+00:00 [running]> on host 93aa310e5d41
[2023-07-11T12:19:05.459+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='train_ordinal_impute' AIRFLOW_CTX_EXECUTION_DATE='2023-07-11T12:17:54.699607+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-11T12:17:54.699607+00:00'
[2023-07-11T12:19:05.494+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/imputers.py", line 38, in train_ordinal_impute
    with open(imputer_path, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-07-11T12:19:05.514+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=train_ordinal_impute, execution_date=20230711T121754, start_date=20230711T121905, end_date=20230711T121905
[2023-07-11T12:19:05.538+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 490 for task train_ordinal_impute (expected str, bytes or os.PathLike object, not NoneType; 544)
[2023-07-11T12:19:05.587+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T12:19:05.619+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
