[2023-07-10T14:55:46.442+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.X_test manual__2023-07-10T14:54:39.615731+00:00 [queued]>
[2023-07-10T14:55:46.470+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.X_test manual__2023-07-10T14:54:39.615731+00:00 [queued]>
[2023-07-10T14:55:46.471+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T14:55:46.508+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): X_test> on 2023-07-10 14:54:39.615731+00:00
[2023-07-10T14:55:46.524+0000] {standard_task_runner.py:57} INFO - Started process 1364 to run task
[2023-07-10T14:55:46.543+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'X_test', 'manual__2023-07-10T14:54:39.615731+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmpk6nncm1j']
[2023-07-10T14:55:46.544+0000] {standard_task_runner.py:85} INFO - Job 324: Subtask X_test
[2023-07-10T14:55:46.704+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.X_test manual__2023-07-10T14:54:39.615731+00:00 [running]> on host 93aa310e5d41
[2023-07-10T14:55:46.959+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='X_test' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T14:54:39.615731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T14:54:39.615731+00:00'
[2023-07-10T14:55:46.992+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/train_test_pull.py", line 18, in load_X_test
    X_test.to_csv(save_path, index=False)
AttributeError: 'NoneType' object has no attribute 'to_csv'
[2023-07-10T14:55:47.014+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=X_test, execution_date=20230710T145439, start_date=20230710T145546, end_date=20230710T145547
[2023-07-10T14:55:47.047+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 324 for task X_test ('NoneType' object has no attribute 'to_csv'; 1364)
[2023-07-10T14:55:47.109+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T14:55:47.147+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
