[2023-07-12T13:26:56.344+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.transform_ordinal_test manual__2023-07-12T13:25:40.792504+00:00 [queued]>
[2023-07-12T13:26:56.371+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.transform_ordinal_test manual__2023-07-12T13:25:40.792504+00:00 [queued]>
[2023-07-12T13:26:56.372+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-12T13:26:56.403+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transform_ordinal_test> on 2023-07-12 13:25:40.792504+00:00
[2023-07-12T13:26:56.414+0000] {standard_task_runner.py:57} INFO - Started process 3994 to run task
[2023-07-12T13:26:56.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'transform_ordinal_test', 'manual__2023-07-12T13:25:40.792504+00:00', '--job-id', '766', '--raw', '--subdir', 'DAGS_FOLDER/dagfile.py', '--cfg-path', '/tmp/tmp0s0ed5tp']
[2023-07-12T13:26:56.424+0000] {standard_task_runner.py:85} INFO - Job 766: Subtask transform_ordinal_test
[2023-07-12T13:26:56.519+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.transform_ordinal_test manual__2023-07-12T13:25:40.792504+00:00 [running]> on host 93aa310e5d41
[2023-07-12T13:26:56.710+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='transform_ordinal_test' AIRFLOW_CTX_EXECUTION_DATE='2023-07-12T13:25:40.792504+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-12T13:25:40.792504+00:00'
[2023-07-12T13:26:56.736+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/scalers.py", line 55, in transform_ordinal_test
    with open(ordinal_scaler_path, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-07-12T13:26:56.757+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=transform_ordinal_test, execution_date=20230712T132540, start_date=20230712T132656, end_date=20230712T132656
[2023-07-12T13:26:56.803+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 766 for task transform_ordinal_test (expected str, bytes or os.PathLike object, not NoneType; 3994)
[2023-07-12T13:26:56.839+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-12T13:26:56.874+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
