[2023-07-10T07:16:23.822+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.merge_features manual__2023-07-10T07:15:44.411742+00:00 [queued]>
[2023-07-10T07:16:23.855+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.merge_features manual__2023-07-10T07:15:44.411742+00:00 [queued]>
[2023-07-10T07:16:23.855+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T07:16:23.897+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): merge_features> on 2023-07-10 07:15:44.411742+00:00
[2023-07-10T07:16:23.911+0000] {standard_task_runner.py:57} INFO - Started process 680 to run task
[2023-07-10T07:16:23.936+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'merge_features', 'manual__2023-07-10T07:15:44.411742+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmp_0i08t0o']
[2023-07-10T07:16:23.937+0000] {standard_task_runner.py:85} INFO - Job 166: Subtask merge_features
[2023-07-10T07:16:24.192+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.merge_features manual__2023-07-10T07:15:44.411742+00:00 [running]> on host 4e174eed6322
[2023-07-10T07:16:24.616+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='merge_features' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T07:15:44.411742+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T07:15:44.411742+00:00'
[2023-07-10T07:16:24.689+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/data/merge_features.py", line 15, in merge_features
    concatenated_df = pd.concat([df1, df2], axis=0)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 374, in __init__
    raise ValueError("All objects passed were None")
ValueError: All objects passed were None
[2023-07-10T07:16:24.743+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=merge_features, execution_date=20230710T071544, start_date=20230710T071623, end_date=20230710T071624
[2023-07-10T07:16:24.808+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 166 for task merge_features (All objects passed were None; 680)
[2023-07-10T07:16:24.865+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T07:16:24.917+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
