[2023-07-10T13:01:37.295+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.merge_features manual__2023-07-10T13:00:43.084168+00:00 [queued]>
[2023-07-10T13:01:37.328+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.merge_features manual__2023-07-10T13:00:43.084168+00:00 [queued]>
[2023-07-10T13:01:37.329+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T13:01:37.365+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): merge_features> on 2023-07-10 13:00:43.084168+00:00
[2023-07-10T13:01:37.383+0000] {standard_task_runner.py:57} INFO - Started process 2124 to run task
[2023-07-10T13:01:37.395+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'merge_features', 'manual__2023-07-10T13:00:43.084168+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmp2tt1hd4v']
[2023-07-10T13:01:37.397+0000] {standard_task_runner.py:85} INFO - Job 232: Subtask merge_features
[2023-07-10T13:01:37.625+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.merge_features manual__2023-07-10T13:00:43.084168+00:00 [running]> on host 6998c1ab8829
[2023-07-10T13:01:37.925+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='merge_features' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T13:00:43.084168+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T13:00:43.084168+00:00'
[2023-07-10T13:01:38.302+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/data/merge_features.py", line 23, in merge_features
    df.to_csv('DATAFRAME.csv', ignore_index=True)
TypeError: to_csv() got an unexpected keyword argument 'ignore_index'
[2023-07-10T13:01:38.329+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=merge_features, execution_date=20230710T130043, start_date=20230710T130137, end_date=20230710T130138
[2023-07-10T13:01:38.364+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 232 for task merge_features (to_csv() got an unexpected keyword argument 'ignore_index'; 2124)
[2023-07-10T13:01:38.398+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T13:01:38.437+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
