[2023-07-10T14:55:40.562+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.y_train manual__2023-07-10T14:54:39.615731+00:00 [queued]>
[2023-07-10T14:55:40.616+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.y_train manual__2023-07-10T14:54:39.615731+00:00 [queued]>
[2023-07-10T14:55:40.616+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T14:55:40.743+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): y_train> on 2023-07-10 14:54:39.615731+00:00
[2023-07-10T14:55:40.830+0000] {standard_task_runner.py:57} INFO - Started process 1361 to run task
[2023-07-10T14:55:40.885+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'y_train', 'manual__2023-07-10T14:54:39.615731+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmpgb8snnz2']
[2023-07-10T14:55:40.910+0000] {standard_task_runner.py:85} INFO - Job 321: Subtask y_train
[2023-07-10T14:55:41.236+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.y_train manual__2023-07-10T14:54:39.615731+00:00 [running]> on host 93aa310e5d41
[2023-07-10T14:55:42.099+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='y_train' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T14:54:39.615731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T14:54:39.615731+00:00'
[2023-07-10T14:55:42.310+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/train_test_pull.py", line 27, in load_y_train
    y_train.to_csv(save_path, index=False)
AttributeError: 'NoneType' object has no attribute 'to_csv'
[2023-07-10T14:55:42.353+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=y_train, execution_date=20230710T145439, start_date=20230710T145540, end_date=20230710T145542
[2023-07-10T14:55:42.466+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 321 for task y_train ('NoneType' object has no attribute 'to_csv'; 1361)
[2023-07-10T14:55:42.599+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T14:55:42.892+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
