[2023-07-10T14:59:51.011+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.X_train manual__2023-07-10T14:59:01.384651+00:00 [queued]>
[2023-07-10T14:59:52.223+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.X_train manual__2023-07-10T14:59:01.384651+00:00 [queued]>
[2023-07-10T14:59:52.233+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10T15:00:03.349+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): X_train> on 2023-07-10 14:59:01.384651+00:00
[2023-07-10T15:00:05.086+0000] {standard_task_runner.py:57} INFO - Started process 1552 to run task
[2023-07-10T15:00:11.837+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'X_train', 'manual__2023-07-10T14:59:01.384651+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/preprocess_dagfile.py', '--cfg-path', '/tmp/tmplj2xbl5h']
[2023-07-10T15:00:11.853+0000] {standard_task_runner.py:85} INFO - Job 335: Subtask X_train
[2023-07-10T15:00:13.220+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.X_train manual__2023-07-10T14:59:01.384651+00:00 [running]> on host 93aa310e5d41
[2023-07-10T15:00:14.255+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='X_train' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T14:59:01.384651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T14:59:01.384651+00:00'
[2023-07-10T15:00:15.238+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/train_test_pull.py", line 9, in load_X_train
    X_train.to_csv(save_path, index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/raw/X_train.csv'
[2023-07-10T15:00:15.352+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=X_train, execution_date=20230710T145901, start_date=20230710T145951, end_date=20230710T150015
[2023-07-10T15:00:15.433+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 335 for task X_train ([Errno 2] No such file or directory: '/data/raw/X_train.csv'; 1552)
[2023-07-10T15:00:15.586+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10T15:00:15.739+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
