[2023-07-12T10:54:29.346+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.clean_age_feature manual__2023-07-12T10:53:57.948881+00:00 [queued]>
[2023-07-12T10:54:29.385+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.clean_age_feature manual__2023-07-12T10:53:57.948881+00:00 [queued]>
[2023-07-12T10:54:29.385+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-12T10:54:29.444+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): clean_age_feature> on 2023-07-12 10:53:57.948881+00:00
[2023-07-12T10:54:29.466+0000] {standard_task_runner.py:57} INFO - Started process 944 to run task
[2023-07-12T10:54:29.488+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'clean_age_feature', 'manual__2023-07-12T10:53:57.948881+00:00', '--job-id', '571', '--raw', '--subdir', 'DAGS_FOLDER/dagfile.py', '--cfg-path', '/tmp/tmp298og6jp']
[2023-07-12T10:54:29.491+0000] {standard_task_runner.py:85} INFO - Job 571: Subtask clean_age_feature
[2023-07-12T10:54:29.743+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.clean_age_feature manual__2023-07-12T10:53:57.948881+00:00 [running]> on host 93aa310e5d41
[2023-07-12T10:54:30.234+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='clean_age_feature' AIRFLOW_CTX_EXECUTION_DATE='2023-07-12T10:53:57.948881+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-12T10:53:57.948881+00:00'
[2023-07-12T10:54:30.301+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/data/clean_age_feature.py", line 16, in clean_age_feature
    df = pd.read_csv(num_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/src/data/../../data/interim/num_cols.csv'
[2023-07-12T10:54:30.360+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=clean_age_feature, execution_date=20230712T105357, start_date=20230712T105429, end_date=20230712T105430
[2023-07-12T10:54:30.415+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 571 for task clean_age_feature ([Errno 2] No such file or directory: '/opt/airflow/dags/src/data/../../data/interim/num_cols.csv'; 944)
[2023-07-12T10:54:30.468+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-12T10:54:30.539+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
