[2023-07-12T11:51:18.892+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.fit_ordinal_imputer manual__2023-07-12T11:50:06.432063+00:00 [queued]>
[2023-07-12T11:51:18.916+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.fit_ordinal_imputer manual__2023-07-12T11:50:06.432063+00:00 [queued]>
[2023-07-12T11:51:18.917+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-12T11:51:18.975+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fit_ordinal_imputer> on 2023-07-12 11:50:06.432063+00:00
[2023-07-12T11:51:18.989+0000] {standard_task_runner.py:57} INFO - Started process 2013 to run task
[2023-07-12T11:51:19.022+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'fit_ordinal_imputer', 'manual__2023-07-12T11:50:06.432063+00:00', '--job-id', '620', '--raw', '--subdir', 'DAGS_FOLDER/dagfile.py', '--cfg-path', '/tmp/tmpng3dp8we']
[2023-07-12T11:51:19.025+0000] {standard_task_runner.py:85} INFO - Job 620: Subtask fit_ordinal_imputer
[2023-07-12T11:51:19.183+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.fit_ordinal_imputer manual__2023-07-12T11:50:06.432063+00:00 [running]> on host 93aa310e5d41
[2023-07-12T11:51:19.448+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='fit_ordinal_imputer' AIRFLOW_CTX_EXECUTION_DATE='2023-07-12T11:50:06.432063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-12T11:50:06.432063+00:00'
[2023-07-12T11:51:19.483+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/imputers.py", line 16, in fit_ordinal_imputer
    imputer.fit(X_train)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/impute/_base.py", line 319, in fit
    X = self._validate_input(X, in_fit=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/impute/_base.py", line 287, in _validate_input
    raise ve
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/impute/_base.py", line 276, in _validate_input
    copy=self.copy,
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 765, in check_array
    "if it contains a single sample.".format(array)
ValueError: Expected 2D array, got scalar array instead:
array=/opt/***/dags/src/preprocess/../../data/interim/train_ordinal.csv.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
[2023-07-12T11:51:19.515+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=fit_ordinal_imputer, execution_date=20230712T115006, start_date=20230712T115118, end_date=20230712T115119
[2023-07-12T11:51:19.543+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 620 for task fit_ordinal_imputer (Expected 2D array, got scalar array instead:
array=/opt/***/dags/src/preprocess/../../data/interim/train_ordinal.csv.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.; 2013)
[2023-07-12T11:51:19.587+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-12T11:51:19.641+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
