[2023-07-12T12:28:02.239+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.X_train_ordinal_impute manual__2023-07-12T12:26:50.691922+00:00 [queued]>
[2023-07-12T12:28:02.269+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.X_train_ordinal_impute manual__2023-07-12T12:26:50.691922+00:00 [queued]>
[2023-07-12T12:28:02.270+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-12T12:28:02.323+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): X_train_ordinal_impute> on 2023-07-12 12:26:50.691922+00:00
[2023-07-12T12:28:02.339+0000] {standard_task_runner.py:57} INFO - Started process 2749 to run task
[2023-07-12T12:28:02.352+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'X_train_ordinal_impute', 'manual__2023-07-12T12:26:50.691922+00:00', '--job-id', '666', '--raw', '--subdir', 'DAGS_FOLDER/dagfile.py', '--cfg-path', '/tmp/tmp1z6hya8m']
[2023-07-12T12:28:02.353+0000] {standard_task_runner.py:85} INFO - Job 666: Subtask X_train_ordinal_impute
[2023-07-12T12:28:02.458+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.X_train_ordinal_impute manual__2023-07-12T12:26:50.691922+00:00 [running]> on host 93aa310e5d41
[2023-07-12T12:28:02.735+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='X_train_ordinal_impute' AIRFLOW_CTX_EXECUTION_DATE='2023-07-12T12:26:50.691922+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-12T12:26:50.691922+00:00'
[2023-07-12T12:28:02.811+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/imputers.py", line 49, in X_train_ordinal_impute
    X_train_ordinal_imputed.to_csv(X_train_ordinal_imputed_path, index=False)
AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'
[2023-07-12T12:28:02.835+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=X_train_ordinal_impute, execution_date=20230712T122650, start_date=20230712T122802, end_date=20230712T122802
[2023-07-12T12:28:02.864+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 666 for task X_train_ordinal_impute ('numpy.ndarray' object has no attribute 'to_csv'; 2749)
[2023-07-12T12:28:02.887+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-12T12:28:02.937+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
