[2023-07-12T12:25:33.733+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.X_train_ordinal_impute manual__2023-07-12T12:24:18.308430+00:00 [queued]>
[2023-07-12T12:25:33.764+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.X_train_ordinal_impute manual__2023-07-12T12:24:18.308430+00:00 [queued]>
[2023-07-12T12:25:33.765+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-12T12:25:33.814+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): X_train_ordinal_impute> on 2023-07-12 12:24:18.308430+00:00
[2023-07-12T12:25:33.837+0000] {standard_task_runner.py:57} INFO - Started process 2671 to run task
[2023-07-12T12:25:33.852+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'X_train_ordinal_impute', 'manual__2023-07-12T12:24:18.308430+00:00', '--job-id', '654', '--raw', '--subdir', 'DAGS_FOLDER/dagfile.py', '--cfg-path', '/tmp/tmp_817rwbv']
[2023-07-12T12:25:33.854+0000] {standard_task_runner.py:85} INFO - Job 654: Subtask X_train_ordinal_impute
[2023-07-12T12:25:34.079+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.X_train_ordinal_impute manual__2023-07-12T12:24:18.308430+00:00 [running]> on host 93aa310e5d41
[2023-07-12T12:25:34.528+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='X_train_ordinal_impute' AIRFLOW_CTX_EXECUTION_DATE='2023-07-12T12:24:18.308430+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-12T12:24:18.308430+00:00'
[2023-07-12T12:25:34.560+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/imputers.py", line 37, in X_train_ordinal_impute
    imputer_path = ti.xcom_push(task_ids="fit_ordinal_imputer", key="imputer_path")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_push() got an unexpected keyword argument 'task_ids'
[2023-07-12T12:25:34.640+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=X_train_ordinal_impute, execution_date=20230712T122418, start_date=20230712T122533, end_date=20230712T122534
[2023-07-12T12:25:34.715+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 654 for task X_train_ordinal_impute (xcom_push() got an unexpected keyword argument 'task_ids'; 2671)
[2023-07-12T12:25:34.848+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-12T12:25:35.002+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
