[2023-07-12T13:54:50.053+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.fit_categorical_encoder manual__2023-07-12T13:53:46.787197+00:00 [queued]>
[2023-07-12T13:54:50.092+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thyroid_preprocessing_DAG.fit_categorical_encoder manual__2023-07-12T13:53:46.787197+00:00 [queued]>
[2023-07-12T13:54:50.092+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-12T13:54:50.125+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): fit_categorical_encoder> on 2023-07-12 13:53:46.787197+00:00
[2023-07-12T13:54:50.149+0000] {standard_task_runner.py:57} INFO - Started process 4628 to run task
[2023-07-12T13:54:50.167+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'thyroid_preprocessing_DAG', 'fit_categorical_encoder', 'manual__2023-07-12T13:53:46.787197+00:00', '--job-id', '833', '--raw', '--subdir', 'DAGS_FOLDER/dagfile.py', '--cfg-path', '/tmp/tmpuadg_lxr']
[2023-07-12T13:54:50.168+0000] {standard_task_runner.py:85} INFO - Job 833: Subtask fit_categorical_encoder
[2023-07-12T13:54:50.336+0000] {task_command.py:410} INFO - Running <TaskInstance: thyroid_preprocessing_DAG.fit_categorical_encoder manual__2023-07-12T13:53:46.787197+00:00 [running]> on host 93aa310e5d41
[2023-07-12T13:54:50.989+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='damirbogdan39@gmail.com' AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='thyroid_preprocessing_DAG' AIRFLOW_CTX_TASK_ID='fit_categorical_encoder' AIRFLOW_CTX_EXECUTION_DATE='2023-07-12T13:53:46.787197+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-12T13:53:46.787197+00:00'
[2023-07-12T13:54:51.087+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/preprocess/scalers.py", line 124, in fit_categorical_encoder
    with open(categorical_encoder_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/src/preprocess/../../models/encoders/categorical_encoder.pkl'
[2023-07-12T13:54:51.122+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=thyroid_preprocessing_DAG, task_id=fit_categorical_encoder, execution_date=20230712T135346, start_date=20230712T135450, end_date=20230712T135451
[2023-07-12T13:54:51.188+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 833 for task fit_categorical_encoder ([Errno 2] No such file or directory: '/opt/airflow/dags/src/preprocess/../../models/encoders/categorical_encoder.pkl'; 4628)
[2023-07-12T13:54:51.297+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-12T13:54:51.453+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
